/* inttypes.h —— BORUIX libc：定宽整数格式化/扫描宏（阶段 6 / 3P6-2）。
 *
 * **为什么需要它**：clang 自带的 `inttypes.h` 只有 `#include_next <inttypes.h>`，真正的定义
 * 必须由系统提供；tcc 的源码大量使用 `PRId64`/`PRIu64` 一类宏。
 *
 * **宏的值是实测得出的，不是抄的**：本目标下 `int_fast16_t` 是 `short`、`int_fast32_t` 是 `int`
 * （不是 LP64 常见的 `long`）。用 `_Static_assert` 探针确认后才写死这里——猜的话 PRI 宏会与实际
 * 类型不符，printf 输出静默错位（探针见 tcc-on-boruix/boruix/_probe_types.c）。
 */
#ifndef _BORUIX_INTTYPES_H
#define _BORUIX_INTTYPES_H

#include "boruix_ctypes.h"
#include <stdint.h>   /* intmax_t / uintmax_t 由编译器内置提供 */

#ifdef __cplusplus
extern "C" {
#endif

typedef struct { intmax_t quot; intmax_t rem; } imaxdiv_t;

intmax_t  imaxabs(intmax_t j);
imaxdiv_t imaxdiv(intmax_t numer, intmax_t denom);
intmax_t  strtoimax(const char *nptr, char **endptr, int base);
uintmax_t strtoumax(const char *nptr, char **endptr, int base);

/* ---- 格式化宏（PRI*）---- */
#define PRId8        "d"
#define PRIi8        "i"
#define PRIo8        "o"
#define PRIu8        "u"
#define PRIx8        "x"
#define PRIX8        "X"
#define PRId16       "d"
#define PRIi16       "i"
#define PRIo16       "o"
#define PRIu16       "u"
#define PRIx16       "x"
#define PRIX16       "X"
#define PRId32       "d"
#define PRIi32       "i"
#define PRIo32       "o"
#define PRIu32       "u"
#define PRIx32       "x"
#define PRIX32       "X"
#define PRId64       "ld"
#define PRIi64       "li"
#define PRIo64       "lo"
#define PRIu64       "lu"
#define PRIx64       "lx"
#define PRIX64       "lX"
#define PRIdLEAST8   "d"
#define PRIiLEAST8   "i"
#define PRIoLEAST8   "o"
#define PRIuLEAST8   "u"
#define PRIxLEAST8   "x"
#define PRIXLEAST8   "X"
#define PRIdLEAST16  "d"
#define PRIiLEAST16  "i"
#define PRIoLEAST16  "o"
#define PRIuLEAST16  "u"
#define PRIxLEAST16  "x"
#define PRIXLEAST16  "X"
#define PRIdLEAST32  "d"
#define PRIiLEAST32  "i"
#define PRIoLEAST32  "o"
#define PRIuLEAST32  "u"
#define PRIxLEAST32  "x"
#define PRIXLEAST32  "X"
#define PRIdLEAST64  "ld"
#define PRIiLEAST64  "li"
#define PRIoLEAST64  "lo"
#define PRIuLEAST64  "lu"
#define PRIxLEAST64  "lx"
#define PRIXLEAST64  "lX"
#define PRIdFAST8    "d"
#define PRIiFAST8    "i"
#define PRIoFAST8    "o"
#define PRIuFAST8    "u"
#define PRIxFAST8    "x"
#define PRIXFAST8    "X"
#define PRIdFAST16   "d"
#define PRIiFAST16   "i"
#define PRIoFAST16   "o"
#define PRIuFAST16   "u"
#define PRIxFAST16   "x"
#define PRIXFAST16   "X"
#define PRIdFAST32   "d"
#define PRIiFAST32   "i"
#define PRIoFAST32   "o"
#define PRIuFAST32   "u"
#define PRIxFAST32   "x"
#define PRIXFAST32   "X"
#define PRIdFAST64   "ld"
#define PRIiFAST64   "li"
#define PRIoFAST64   "lo"
#define PRIuFAST64   "lu"
#define PRIxFAST64   "lx"
#define PRIXFAST64   "lX"
#define PRIdMAX      "ld"
#define PRIiMAX      "li"
#define PRIoMAX      "lo"
#define PRIuMAX      "lu"
#define PRIxMAX      "lx"
#define PRIXMAX      "lX"
#define PRIdPTR      "ld"
#define PRIiPTR      "li"
#define PRIoPTR      "lo"
#define PRIuPTR      "lu"
#define PRIxPTR      "lx"
#define PRIXPTR      "lX"

/* ---- 扫描宏（SCN*）---- */
#define SCNd8        "hhd"
#define SCNi8        "hhi"
#define SCNo8        "hho"
#define SCNu8        "hhu"
#define SCNx8        "hhx"
#define SCNX8        "hhX"
#define SCNd16       "hd"
#define SCNi16       "hi"
#define SCNo16       "ho"
#define SCNu16       "hu"
#define SCNx16       "hx"
#define SCNX16       "hX"
#define SCNd32       "d"
#define SCNi32       "i"
#define SCNo32       "o"
#define SCNu32       "u"
#define SCNx32       "x"
#define SCNX32       "X"
#define SCNd64       "ld"
#define SCNi64       "li"
#define SCNo64       "lo"
#define SCNu64       "lu"
#define SCNx64       "lx"
#define SCNX64       "lX"
#define SCNdLEAST8   "hhd"
#define SCNiLEAST8   "hhi"
#define SCNoLEAST8   "hho"
#define SCNuLEAST8   "hhu"
#define SCNxLEAST8   "hhx"
#define SCNXLEAST8   "hhX"
#define SCNdLEAST16  "hd"
#define SCNiLEAST16  "hi"
#define SCNoLEAST16  "ho"
#define SCNuLEAST16  "hu"
#define SCNxLEAST16  "hx"
#define SCNXLEAST16  "hX"
#define SCNdLEAST32  "d"
#define SCNiLEAST32  "i"
#define SCNoLEAST32  "o"
#define SCNuLEAST32  "u"
#define SCNxLEAST32  "x"
#define SCNXLEAST32  "X"
#define SCNdLEAST64  "ld"
#define SCNiLEAST64  "li"
#define SCNoLEAST64  "lo"
#define SCNuLEAST64  "lu"
#define SCNxLEAST64  "lx"
#define SCNXLEAST64  "lX"
#define SCNdFAST8    "hhd"
#define SCNiFAST8    "hhi"
#define SCNoFAST8    "hho"
#define SCNuFAST8    "hhu"
#define SCNxFAST8    "hhx"
#define SCNXFAST8    "hhX"
#define SCNdFAST16   "hd"
#define SCNiFAST16   "hi"
#define SCNoFAST16   "ho"
#define SCNuFAST16   "hu"
#define SCNxFAST16   "hx"
#define SCNXFAST16   "hX"
#define SCNdFAST32   "d"
#define SCNiFAST32   "i"
#define SCNoFAST32   "o"
#define SCNuFAST32   "u"
#define SCNxFAST32   "x"
#define SCNXFAST32   "X"
#define SCNdFAST64   "ld"
#define SCNiFAST64   "li"
#define SCNoFAST64   "lo"
#define SCNuFAST64   "lu"
#define SCNxFAST64   "lx"
#define SCNXFAST64   "lX"
#define SCNdMAX      "ld"
#define SCNiMAX      "li"
#define SCNoMAX      "lo"
#define SCNuMAX      "lu"
#define SCNxMAX      "lx"
#define SCNXMAX      "lX"
#define SCNdPTR      "ld"
#define SCNiPTR      "li"
#define SCNoPTR      "lo"
#define SCNuPTR      "lu"
#define SCNxPTR      "lx"
#define SCNXPTR      "lX"

#ifdef __cplusplus
}
#endif

#endif /* _BORUIX_INTTYPES_H */